{"uuid": "dcaf0948-3af7-420a-840b-638e36cc3cfb", "children": ["f8137e87-ebc7-4381-b492-b73c1a8c1561"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "webium.errors.WebiumException: Can't open page without url\n", "trace": "  File \"C:\\Users\\79605\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\79605\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\79605\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"C:\\Development\\autotests\\conftest.py\", line 19, in driver\n    url=''\n  File \"C:\\Development\\autotests\\base\\ui\\login_page\\page_login.py\", line 8, in __init__\n    self.open()\n  File \"C:\\Development\\autotests\\venv\\lib\\site-packages\\webium\\base_page.py\", line 62, in open\n    raise WebiumException('Can\\'t open page without url')\n"}, "start": 1608992178923, "stop": 1608992181865}], "start": 1608992178923, "stop": 1608992181874}